<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="MAIN" Id="{cf35716e-8769-4551-8e5a-9323d324a38e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	GVL.In := 1;
	GVL.Out := 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="18" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>